---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-workload
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: applications-apps
  source:
    repoURL: git@github.com:Mohit-Verma-1688/ArgoCD-Demo.git
    targetRevision: HEAD
    path: argo-apps
    helm:
      values: |
        spec:
          destination:
            server: https://kubernetes.default.svc
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true 
