---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: applications-apps
  source:
    repoURL: git@github.com:Mohit-Verma-1688/ArgoCD-Demo.git 
    targetRevision: HEAD
    path: workloads/argo-events
    helm:
      releaseName: argo-eventsw
      valueFiles:
       - values.yaml  
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  syncPolicy:
    automated:
      prune: true    
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m 
