---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: php-frontend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: applications-apps
  source:
    repoURL: git@github.com:Mohit-Verma-1688/ArgoCD-Demo.git 
    targetRevision: HEAD
    path: workloads/phpapp
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: demo-webapp
  syncPolicy:
    automated:
      prune: true    
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m 
